import os
import re

names = {
    "LavenderPokemart": "LavenderTown_Mart",
    "Route7_Route8Tunnel": "SaffronCity_Tunnel_SW",
    "PokemonLeague5": "PokemonLeague_ChampionsRoom",
    "SlowpokeWell2": "SlowpokeWell_B2F",
    "IndigoJunction": "ReceptionGate",
    "EcruteakSageOffice": "EcruteakCity_SageOffice2",
    "GoldenrodPokecenter": "GoldenrodCity_PokemonCenter",
    "MtMoon1": "MtMoon_Cave",
    "CeladonCityDepartmentStore6": "CeladonCity_DepartmentStore_RoofDay",
    "IndigoPlateauPokeCenter": "IndigoPlateau_PokemonCenter",
    "CeladonCityDepartmentStore5": "CeladonCity_DepartmentStore_5F",
    "RuinsOfAlphOffice": "RuinsOfAlph_Lab",
    "PlayersHouse2": "NewBarkTown_PlayersHouse_2F",
    "CeruleanCityGym": "CeruleanCity_Gym",
    "Route5_SaffronGate": "Gate_SaffronCity_Route5",
    "MtMoonTest": "MtMoon_Outside",
    "PewterCityHouse1": "PewterCity_House1",
    "Route36_RuinsGate": "Gate_RuinsOfAlph_Route36",
    "CeruleanPokecenter": "CeruleanCity_PokemonCenter",
    "TinTower7": "TinTower_7F",
    "PalletTownHouse3": "PalletTown_House3",
    "Fuchsia": "FuchsiaCity_SafariZoneBeach",
    "MtSilverPokecenter": "MtSilver_PokemonCenter",
    "RuinsOfAlphC_1": "RuinsOfAlph_WordsRoom1",
    "Route31_VioletGate": "Gate_Route31_VioletCity",
    "GoldenrodGym": "GoldenrodCity_Gym",
    "Route30MrPokemonHouse": "Route30_MrPokemonsHouse",
    "CeruleanCave_3": "CeruleanCave_B2F",
    "SproutTower2": "SproutTower_2F",
    "PowerPlant2": "Route10_PowerPlantBackRoom",
    "DiglettsCave2": "DiglettsCave_EntranceSouth",
    "OlivineCityPort": "OlivineCity_PortOutside",
    "BlackthornHouse1": "BlackthornCity_House1",
    "MtSilverSummitTestNight": "MtSilver_SummitNight",
    "Route27House": "Route27_House",
    "BurnedTower1": "BurnedTower_1F",
    "GoldenrodDepartmentStore6": "GoldenrodCity_DepartmentStore_6F",
    "MtSilver8": "MtSilver_3F",
    "FuchsiaCitySafariZoneMountain": "FuchsiaCity_SafariZoneMountain",
    "CeladonApartments5": "CeladonCity_Apartments_RoofHouse",
    "CeladonCityDepartmentStore4": "CeladonCity_DepartmentStore_4F",
    "SafariZoneGatePokecenter": "SafariZoneGate_PokemonCenter",
    "HallOfFame": "PokemonLeague_HallOfFame",
    "GoldenrodHouse3": "GoldenrodCity_House3",
    "CeladonCityDepartmentStore1": "CeladonCity_DepartmentStore_1F",
    "VictoryRoad3": "VictoryRoadKanto_1F",
    "SeafoamIslands3": "SeafoamIslands_B1F",
    "CinnabarVolcano1": "SeafoamIslands_SecretCave",
    "VioletPokemart": "VioletCity_Mart",
    "BlackthornHouse3": "BlackthornCity_House3",
    "GoldenRodUnderground1": "GoldenrodCity_UndergroundEntrance",
    "Route7TunnelEnter": "Route7_TunnelEntrance",
    "RocketHideout2": "RocketHideout_B2F",
    "OlivineCafe": "OlivineCity_Cafe",
    "Route26House1": "Route26_House1",
    "Route2_ViridianForestGate": "Gate_Route2_ViridianForest",
    "VioletCityGym": "VioletCity_Gym",
    "NationalParkGates": "Gate_NationalPark",
    "SeafoamIslands2": "SeafoamIslands_Gym",
    "NewBarkTownHouse2": "NewBarkTown_House2",
    "VermilionCityHouse1": "VermilionCity_House1",
    "PlayersHouse1": "NewBarkTown_PlayersHouse_1F",
    "Fuchsia_Route15Gate": "FuchsiaCity_Route15_Gate",
    "Route16_Route18Gate": "Gate_FuchsiaCity_Route18",
    "Route5House": "Route5_House",
    "OlivineHouse1": "OlivineCity_House1",
    "CherrygroveHouse1": "CherrygroveCity_House1",
    "MtSilver": "MtSilver_Outside",
    "RockTunnel2": "RockTunnel_1F",
    "SaffronCitySilphCo": "SaffronCity_SilphCo",
    "MahoganyPokecenter": "MahoganyTown_PokemonCenter",
    "SaffronPokemart": "SaffronCity_Mart",
    "VioletCityTrainerSchool": "VioletCity_TrainerSchool",
    "GoldenrodUnderground2": "GoldenrodCity_UndergroundTunnel",
    "CeladonCityGym": "CeladonCity_Gym",
    "Ecruteak_38Gate": "Gate_EcruteakCity_Route38",
    "RuinsOfAlph2": "RuinsOfAlph_PuzzleAndRewardChambers",
    "Gate": "Gate_Route43",
    "Fuchsia_Route19Gate": "FuchsiaCity_Route19_Gate",
    "TinTower5": "TinTower_5F",
    "LavenderTownHouse3": "LavenderTown_House3",
    "OlivinePokemart": "OlivineCity_Mart",
    "BattleTowerOuter": "BattleTower_Outside",
    "SaffronCityHouse2": "SaffronCity_House1",
    "FuchsiaCityHouse3": "FuchsiaCity_House2",
    "NewBarkTownLab": "NewBarkTown_Lab",
    "Route6TunnelEnter": "Route6_TunnelEntrance",
    "Cherrygrove_Pokecenter": "CherrygroveCity_PokemonCenter",
    "BlackthornHouse2": "BlackthornCity_House2",
    "BlackthornGym1": "BlackthornCity_Gym",
    "MahoganyGym": "MahoganyTown_Gym",
    "NationalPark": "NationalPark_Normal",
    "DragonsDen2": "DragonsDen_Cavern",
    "EcruteakHouse1": "EcruteakCity_House1",
    "OlivineGym": "OlivineCity_Gym",
    "SSAqua6": "SSAqua_RoomNE",
    "MtSilver2": "MtSilver_1F_WaterfallRoom",
    "ViridianPokecenter": "ViridianCity_PokemonCenter",
    "ViridianCityGym": "ViridianCity_Gym",
    "GoldenrodDepartmentStore1": "GoldenrodCity_DepartmentStore_1F",
    "MtMoonHouse": "MtMoon_Shop",
    "Route16House": "Route16_House",
    "TinTower6": "TinTower_6F",
    "Route39Barn": "Route39_Barn",
    "MtSilverSideTest": "MtSilver_Snow",
    "Route30House": "Route30_House",
    "VermilionCityPortIndoor": "VermilionCity_PortInside",
    "IcePath3": "IcePath_B2F",
    "GoldenrodDepartmentStoreElevator": "GoldenrodCity_DepartmentStoreElevator",
    "CeladonCityApartments1": "CeladonCity_Apartments_1F",
    "CeladonApartments4": "CeladonCity_Apartments_RoofDay",
    "FuchsiaCityHouse1": "FuchsiaCity_House1",
    "CherrygroveHouse2": "CherrygroveCity_House2",
    "CeladonApartments4Night": "CeladonCity_Apartments_RoofNight",
    "CinnabarPokecenter": "CinnabarIsland_PokemonCenter",
    "FuchsiaPokecenter": "FuchsiaCity_PokemonCenter",
    "MtMortar4": "MtMortar_B1F",
    "Goldenrod_35Gate": "Gate_GoldenrodCity_Route35",
    "GoldenrodFlowerShop": "GoldenrodCity_FlowerShop",
    "SSAqua9": "SSAqua_RoomSE",
    "OlivineMarina_0": "OlivineCity_PortInside",
    "DarkCave_2": "DarkCave_NorthSide",
    "GoldenrodUndergroundRocket3": "GoldenrodCity_DepartmentStoreBasement",
    "SaffronCityHouse1": "SaffronCity_CopyCatsHouse_1F",
    "DragonsDen1": "DragonsDen_Entrance",
    "Azalea_Pokecenter": "AzaleaTown_PokemonCenter",
    "CherrygrovePokemart": "CherrygroveCity_Mart",
    "LavenderTownHouse1": "LavenderTown_House1",
    "GoldenrodDepartmentStore2": "GoldenrodCity_DepartmentStore_2F",
    "WhirlIslands3": "WhirlIslands_B2F",
    "GoldenrodRadioTower2": "GoldenrodCity_RadioTower_2F",
    "CherrygroveHouse3": "CherrygroveCity_House3",
    "SSAqua7": "SSAqua_RoomNNE",
    "TinTower9": "TinTower_9F",
    "GoldenrodRadioTower5": "GoldenrodCity_RadioTower_5F",
    "CeruleanCityHouse2": "CeruleanCity_House2",
    "VermilionCityGym": "VermilionCity_Gym",
    "FuchsiaSafariZoneCave": "FuchsiaCity_SafariZoneCave",
    "MtSilverSummitTest": "MtSilver_SummitDay",
    "FuchsiaCitySafariZoneBrush": "FuchsiaCity_SafariZoneBrush",
    "SSAqua": "SSAqua_RoomNW",
    "NewBarkTownHouse1": "NewBarkTown_House1",
    "PokemonLeague3": "PokemonLeague_BrunosRoom",
    "GoldenrodDepartmentStore3": "GoldenrodCity_DepartmentStore_3F",
    "Bellchime_Trail": "BellchimeTrail",
    "PokemonLeague4": "PokemonLeague_KarensRoom",
    "Route4Pokecenter": "Route4_PokemonCenter",
    "SlowpokeWell": "SlowpokeWell_B1F",
    "SSAqua4": "SSAqua_PlayersRoom",
    "DiglettsCave1": "DiglettsCave_EntranceNorth",
    "AzaleaGym": "AzaleaTown_Gym",
    "RuinsOfAlphC_3": "RuinsOfAlph_WordsRoom3",
    "NewMap2": "SSAqua_RoomSSW",
    "PewterCityMuseum1": "PewterCity_Museum_1F",
    "Route32Pokecenter": "Route32_PokemonCenter",
    "RuinsOfAlph1": "RuinsOfAlph_B1F",
    "DiglettsCave3": "DiglettsCave_Tunnel",
    "CeruleanCityHouse1": "CeruleanCity_House1",
    "OlivineLighthouse1": "OlivineCity_Lighthouse",
    "GoldenrodDepartmentStore7": "GoldenrodCity_DepartmentStore_7F",
    "TohjoFalls": "TohjoFalls_Cavern",
    "SproutTower1": "SproutTower_1F",
    "MtSilver5": "MtSilver_MountainSide",
    "EcruteakSageOffice1F": "EcruteakCity_SageOffice1",
    "Celadon_Route16Gate": "Gate_CeladonCity_Route16",
    "WhirlIslands1": "WhirlIslands_1F",
    "PewterPokecenter": "PewterCity_PokemonCenter",
    "GoldenrodHouse2": "GoldenrodCity_House2",
    "FuchsiaPokemart": "FuchsiaCity_Mart",
    "PalletTownLab": "PalletTown_Lab",
    "OlivinePokecenter": "OlivineCity_PokemonCenter",
    "MtMortar2": "MtMortar_1F_North",
    "TinTower8": "TinTower_8F",
    "MtSilver4": "MtSilver_1F_MoltresRoom",
    "MtMortar1": "MtMortar_1F_South",
    "RocketHideout": "RocketHideout_B1F",
    "SSAqua2": "SSAqua_B1F",
    "CeladonHouse2": "CeladonCity_House2",
    "Violet_Pokecenter": "VioletCity_PokemonCenter",
    "CeladonApartments2": "CeladonCity_Apartments_2F",
    "MahoganyShop": "MahoganyTown_Shop",
    "MahoganyHouse1": "MahoganyTown_House1",
    "CeruleanPokemart": "CeruleanCity_Mart",
    "RuinsOfAlphC_2": "RuinsOfAlph_WordsRoom2",
    "AzaleaHouse1": "AzaleaTown_House1",
    "Route29_46Gate": "Gate_Route29_Route46",
    "SproutTower3": "SproutTower_3F",
    "SaffronCityGym": "SaffronCity_Gym",
    "CeruleanCave_1": "CeruleanCave_1F",
    "GoldenrodUndergroundRocket1": "GoldenrodCity_UndergroundSwitches",
    "PalletTownHouse2": "PalletTown_House2",
    "DarkCave_1": "DarkCave_SouthSide",
    "EcruteakTheater": "EcruteakCity_Theater",
    "LavenderPokecenter": "LavenderTown_PokemonCenter",
    "Route121_SafariZoneGate_SafariZoneEntrance": "Route121_SafariZoneGate_SafariZoneEntrance",
    "PokemonLeague1": "PokemonLeague_WillsRoom",
    "TohjoFalls2": "TohjoFalls_GiovanniRoom",
    "Ilex_34Gate": "Gate_IlexForest_Route34",
    "TinTower4": "TinTower_4F",
    "BlackthornPokemart": "BlackthornCity_Mart",
    "FuchsiaCityGym": "FuchsiaCity_Gym",
    "EcruteakPokecenter": "EcruteakCity_PokemonCenter",
    "Mahogany_43Gate": "Gate_MahoganyTown_Route43",
    "Saffron_Route8Gate": "Gate_SaffronCity_Route8",
    "RuinsOfAlphC_4": "RuinsOfAlph_WordsRoom4",
    "TinTower3": "TinTower_3F",
    "SSAqua10": "SSAqua_RoomSW",
    "VermilionPokemart": "VermilionCity_Mart",
    "Azalea_IlexGate": "Gate_AzaleaTown_IlexForest",
    "EcruteakPokemart": "EcruteakCity_Mart",
    "ViridianPokemart": "ViridianCity_Mart",
    "MtSilver1": "MtSilver_1F_ItemRoom",
    "CeladonCityGameCorner": "CeladonCity_GameCorner",
    "GoldenrodDepartmentStore5": "GoldenrodCity_DepartmentStore_5F",
    "CeruleanCityBikeShop": "CeruleanCity_BikeShop",
    "CeladonHouse1": "CeladonCity_House1",
    "DragonsDen3": "DragonsDen_Shrine",
    "CeladonCityDepartmentStore3": "CeladonCity_DepartmentStore_3F",
    "CeruleanCityHouse3": "CeruleanCity_House3",
    "EcruteakGym": "EcruteakCity_Gym",
    "LavenderTownRadioStation": "LavenderTown_RadioStation",
    "SSAqua8": "SSAqua_RoomSSE",
    "SaffronPokecenter": "SaffronCity_PokemonCenter",
    "AzaleaPokemart": "AzaleaTown_Mart",
    "IcePath1": "IcePath_1F",
    "LavenderTownHouse2": "LavenderTown_House2",
    "VermilionPokecenter": "VermilionCity_PokemonCenter",
    "TinTower10": "TinTower_RoofDay",
    "TinTower2": "TinTower_2F",
    "ViridianForest_Route2Gate": "Gate_ViridianForest_Route2",
    "ViridianCityHouse2": "ViridianCity_House2",
    "PokemonLeague2": "PokemonLeague_KogasRoom",
    "CeladonCityDepartmentStore7": "CeladonCity_DepartmentStore_RoofNight",
    "LakeOfRageHouse2": "LakeOfRage_House2",
    "VioletCityHouse2": "VioletCity_House2",
    "Route40_BattleTowerGate": "Gate_Route40_BattleTowerOutside",
    "Route26House2": "Route26_House2",
    "IcePath5": "IcePath_B4F",
    "CeladonPokecenter": "CeladonCity_PokemonCenter",
    "VictoryRoad1": "VictoryRoadKanto_B2F",
    "OlivineHouse3": "OlivineCity_House3",
    "Route2House": "Route2_House",
    "TinTower1": "TinTower_1F",
    "Route9Pokecenter": "Route9_PokemonCenter",
    "SaffronCityCopyCatRoom": "SaffronCity_CopyCatsHouse_2F",
    "GoldenrodRadioTower1": "GoldenrodCity_RadioTower_1F",
    "MtSilverHouse": "Route28_House",
    "WhirlIslands2": "WhirlIslands_B1F",
    "Ecruteak_42Gate": "Gate_EcruteakCity_Route42",
    "UnionCave2": "UnionCave_B1F",
    "GoldenrodBillsHouse": "GoldenrodCity_BillsHouse",
    "BlackthornPokecenter": "BlackthornCity_PokemonCenter",
    "GoldenrodRadioTower": "GoldenrodCity_RadioTower_4F",
    "RocketHideout3": "RocketHideout_B3F",
    "SaffronCityDojoVIP": "SaffronCity_FightingDojoVIP",
    "VermilionCityHouse3": "VermilionCity_House3",
    "Route7_SaffronGate": "Gate_SaffronCity_Route7",
    "CeladonApartments3": "CeladonCity_Apartments_3F",
    "Route25BillsHouse": "Route25_BillsHouse",
    "SafariZoneEntrance_Fuchsia": "FuchsiaCity_SafariZoneEntrance",
    "Route12House": "Route12_House",
    "GoldenrodBikeShop": "GoldenrodCity_BikeShop",
    "CeladonCityDepartmentStore2": "CeladonCity_DepartmentStore_2F",
    "SaffronCityDojo": "SaffronCity_FightingDojo",
    "IcePath4": "IcePath_B3F",
    "LakeOfRageUnderground": "Route19_Cave",
    "ViridianCityHouse1": "ViridianCity_House1",
    "Route34DayCare": "Route34_DayCare",
    "SSAqua3": "SSAqua_CaptainsRoom",
    "PewterPokemart": "PewterCity_Mart",
    "GoldenrodHouse1": "GoldenrodCity_House1",
    "Route32_RuinsGate": "Gate_RuinsOfAlph_Route32",
    "GoldenrodStation": "GoldenrodCity_TrainStation",
    "GoldenrodUndergroundRocket2": "GoldenrodCity_UndergroundStorage",
    "UnionCave3": "UnionCave_B2F",
    "GoldenrodRadioTower3": "GoldenrodCity_RadioTower_3F",
    "TinTower10Night": "TinTower_RoofNight",
    "SeafoamIslands1": "SeafoamIslands_1F",
    "EcruteakHouse2": "EcruteakCity_House2",
    "LavenderTownSoulHouse1": "LavenderTown_SoulHouse",
    "GoldenrodGameCorner": "GoldenrodCity_GameCorner",
    "OlivineHouse2": "OlivineCity_House2",
    "PalletTownRedsHouse2": "PalletTown_RedsHouse_2F",
    "GoldenrodDepartmentStore7Night": "GoldenrodCity_DepartmentStore_7FNight",
    "AzaleaKurtsHouse": "AzaleaTown_KurtsHouse",
    "RockTunnel1": "RockTunnel_B1F",
    "PowerPlant1": "Route10_PowerPlantEntrance",
    "Route5_Route6Tunnel": "SaffronCity_Tunnel_NS",
    "Route5TunnelEnter": "Route5_TunnelEntrance",
    "SaffronTrainStation": "SaffronCity_TrainStation",
    "Route2_Route2Gate": "Gate_Route2",
    "Route8TunnelEnter": "Route8_TunnelEntrance",
    "VioletCityHouse1": "VioletCity_House1",
    "MtMortar3": "MtMortar_2F",
    "SafariZoneEntrance": "SafariZoneGate_SafariZoneEntrance",
    "BurnedTower2": "BurnedTower_B1F",
    "VermilionCityPort1": "VermilionCity_PortOutside",
    "VermilionCityFanClub": "VermilionCity_FanClub",
    "SSAqua1": "SSAqua_1F",
    "PewterCityHouse2": "PewterCity_House2",
    "VermilionCityHouse2": "VermilionCity_House2",
    "PewterCityMuseum2": "PewterCity_Museum_2F",
    "PewterCityGym": "PewterCity_Gym",
    "GoldenrodDepartmentStore4": "GoldenrodCity_DepartmentStore_4F",
    "UnionCave1": "UnionCave_1F",
    "LakeOfRageHouse1": "LakeOfRage_House1",
    "IcePath2": "IcePath_B1F",
    "Route39_Farmhouse": "Route39_FarmHouse",
    "PalletTownRedsHouse1": "PalletTown_RedsHouse_1F",
    "VictoryRoad2": "VictoryRoadKanto_B1F",
    "MtSilver6": "MtSilver_2F",
    "RuinsOfAlph": "RuinsOfAlph_Outside",
    "CeruleanCave_2": "CeruleanCave_B1F",
    "NationalPark2": "NationalPark_BugContest",
    "Saffron_Route6Gate": "Gate_SaffronCity_Route6",
}

undefined_funcs = [
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_ThatWillBe500Please',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_HereAreYourSafariBalls',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_Received30SafariBalls',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_PleaseEnjoyYourself',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_PCIsFull',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_YouNeedPokeblockCase',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_NotEnoughMoney',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_ThatWillBe500Please',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_HereAreYourSafariBalls',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_Received30SafariBalls',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_PleaseEnjoyYourself',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_PCIsFull',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_YouNeedPokeblockCase',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_NotEnoughMoney',
    'Route121_SafariZoneGate_SafariZoneEntrance_Text_NotEnoughMoney',
    'GoldenrodCity_RadioTower_4F5_EventScript_Trigger_NPCS',
    'GoldenrodCity_RadioTower_4F5_EventScript_Trigger_NPCS',
    'Route121_SafariZoneGate_SafariZoneEntrance_EventScript_InfoAttendant',
    'Route121_SafariZoneGate_SafariZoneEntrance_EventScript_WelcomeAttendant',
    'Route121_SafariZoneGate_SafariZoneEntrance_EventScript_InfoAttendant',
]

modify_folder = '/home/andrew/pokehns-expansion/'

func_map = []

for func in undefined_funcs:
    for old, new in names.items():
        if func.startswith(old):
            func_map.append((func, func.replace(old, new, 1)))

print(func_map)

for subdir, dirs, files in os.walk(os.path.join(modify_folder, 'data/maps')):
    for file in files:
        if file == 'scripts.inc' or file == 'map.json':
            filepath = os.path.join(subdir, file)
            with open(filepath) as f:
                s = f.read()
                for old, new in func_map:
                    if old in s:
                        s = re.sub(f'\\b{old}\\b', new, s)
            with open(filepath, "w") as f:
                f.write(s)
